version: '3'

services:
  adminer:
    image: adminer:4.8.1
    container_name: mssql_adminer
    restart: "no"
    environment:
      ADM_INSTALL_MSSQL: "true"
      ADMINER_DEFAULT_SERVER: "mssql"
      ADMINER_DESIGN: "pepa-linha"
      PHP_FPM_INSTALL_MSSQL: "true"
      WORKSPACE_INSTALL_MSSQL: "true"
    ports:
      - 8081:8080

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "mssql"
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_ADMIN_PASSWORD}"
    ports:
      - 1433:1433